### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by im-coder-lg** [im-coder-lg/futura-astrosite#1]
This extends till May of 2024, due to personal commitments. I will use the free time available to try migrate https://futura-py.github.io to Astro. It is much more better to use something like this, for order and comfort. Using JS, the website can be malleable as we wish, just like the timeline.

| The Flash, Season 5 reference
| ---
| "The timeline is malleable" 

So far, the migration has yielded this: https://imcoderlg-futura-astrosite.netlify.app

We must use Netlify or Vercel, whichever works so that the website can be hosted properly. If our CDN idea works, let's stick with Netlify. 

Task list:
- [ ] Refine website
- [ ] Ensure that the website is updated w/ HTML from Futura-Py/futura-py.github.io
- [ ] try adding CDN as test(we shall see how it works)
- [ ] add Astro Community Components
- [ ] modernise website
- [ ] better UI
- [ ] tailwind CSS
- [ ] beautiful and neat icons
- [ ] easter eggs on every corner
- [ ] add workflows
- [ ] add GH pages deployment + vercel?

**Comment by im-coder-lg** [comment]
Delayed indefinitely, if not forever.
